name: extplane-panel
version: "2.0.2-git"
summary: External networked panel for flight simulators
description: |
  External networked panel for flight simulators such
  as X-Plane, FlightGear and Condor
base: core18
confinement: devmode
parts:

parts:
  extplane:
    source: https://github.com/vranki/ExtPlane.git
    plugin: dump

  extplane-panel:
    source: .
    plugin: qmake
    options:
    - -r
    qt-version: qt5
    after: [desktop-qt5, extplane]
    stage-packages:
      - qml-module-qt-labs-settings
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
      - qml-module-qtquick-shapes

apps:
  extplane-panel:
    command: bin/desktop-launch extplane-panel
